version: '3.9'

services:
  backend:
    container_name: backend
    build: ./backend
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      POSTGRES_HOST: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: logs_bdd
      PORT_SERVER: 8000
      CONTRACT: "6A7577c10cD3F595eB2dbB71331D7Bf7223E1Aac"
    volumes:
      - ./backend:/usr/src/app/
    networks:
      - my_network

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      CONTRACT: "0x6A7577c10cD3F595eB2dbB71331D7Bf7223E1Aac"
    volumes:
      - ./frontend:/app/
    networks:
      - my_network

  database:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: logs_bdd
    volumes:
      - ./sql/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
      - ./sql/create_table_volumes.sql:/docker-entrypoint-initdb.d/create_table_volumes.sql
      - ./sql/create_table_logs.sql:/docker-entrypoint-initdb.d/create_table_logs.sql
    networks:
      - my_network
      
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /chemin/local/vers/fullchain.pem:/etc/letsencrypt/live/jeremy.training.real-estate-executive.com/fullchain.pem
      - /chemin/local/vers/privkey.pem:/etc/letsencrypt/live/jeremy.training.real-estate-executive.com/privkey.pem
    depends_on:
      - frontend
    networks:
      - my_network
networks:
  my_network:
    driver: bridge