version: '3.7'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - default  # Utiliser le réseau par défaut
      - network-frontend
    depends_on:
      - database
    environment:
      POSTGRES_HOST: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: logs_bdd
      PORT_SERVER: 8000
      CONTRACT: "6A7577c10cD3F595eB2dbB71331D7Bf7223E1Aac"
    volumes:
      - ./backend:/usr/src/app/
    # Définir un alias pour le service backend
    container_name: backend
    networks_aliases:
      - backend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - default  # Utiliser le réseau par défaut
      - network-frontend
    depends_on:
      - backend
    environment:
      SERVER: http://backend:8000  # Utiliser l'alias du service backend
      CONTRACT: "0x6A7577c10cD3F595eB2dbB71331D7Bf7223E1Aac"
    volumes:
      - ./frontend:/app/
    # Définir un alias pour le service frontend
    container_name: frontend
    networks_aliases:
      - frontend

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: logs_bdd
    # Utiliser le réseau par défaut
    networks:
      - default

    volumes:
      - ./sql/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
      - ./sql/create_table_volumes.sql:/docker-entrypoint-initdb.d/create_table_volumes.sql
      - ./sql/create_table_logs.sql:/docker-entrypoint-initdb.d/create_table_logs.sql

networks:
  default:
    driver: bridge
  network-frontend:
    # Définir un alias pour le réseau frontend
    driver: bridge
    name: network-frontend
